import { createAIClient, aiModelManager, type AIProvider } from '../config/ai-models';

export interface TranslateResult {
  sourceText: string;
  translatedText: string;
  sourceLang: string;
  targetLang: string;
  provider: string;
  model: string;
}

const LANG_MAP: Record<string, string> = {
  auto: '自动检测',
  zh: '中文',
  en: '英语',
  ja: '日语',
  ko: '韩语',
  fr: '法语',
  de: '德语',
  es: '西班牙语',
  ru: '俄语',
};

const MOCK_TRANSLATIONS: Record<string, string> = {
  zh: '这是一段由Mock模式生成的翻译示例文本，用于演示翻译功能在缺少API密钥时的表现。',
  en: 'This is a sample translation text generated by Mock mode, demonstrating the translation feature without an API key.',
  ja: 'これはMockモードによって生成された翻訳のサンプルテキストです。APIキーがない場合の翻訳機能の動作を示しています。',
  ko: '이것은 Mock 모드에서 생성된 번역 샘플 텍스트로, API 키 없이 번역 기능이 작동하는 것을 보여줍니다.',
};

/** 翻译服务 */
class TranslationService {
  async translate(
    text: string,
    targetLang: string,
    sourceLang = 'auto',
    provider?: AIProvider,
    model?: string
  ): Promise<TranslateResult> {
    if (!text?.trim()) throw new Error('翻译文本不能为空');

    const mockMode = process.env.ENABLE_MOCK_MODE === 'true';
    const p = provider || aiModelManager.getDefaultProvider()?.name.toLowerCase() as AIProvider || 'openai';
    const m = model || aiModelManager.getProvider(p as AIProvider)?.defaultModel || 'gpt-4o';

    if (mockMode || !process.env.OPENAI_API_KEY && p === 'openai') {
      // Mock 模式下返回占位翻译
      const langKey = Object.keys(MOCK_TRANSLATIONS).includes(targetLang) ? targetLang : 'en';
      return {
        sourceText: text,
        translatedText: MOCK_TRANSLATIONS[langKey],
        sourceLang: LANG_MAP[sourceLang] || sourceLang,
        targetLang: LANG_MAP[targetLang] || targetLang,
        provider: p,
        model: m,
      };
    }

    const client = createAIClient(p as AIProvider);
    const sysPrompt = `你是一个专业翻译引擎。请将用户提供的文本翻译为${LANG_MAP[targetLang] || targetLang}。${
      sourceLang !== 'auto' ? `源语言为${LANG_MAP[sourceLang] || sourceLang}。` : '请自动检测源语言。'
    }只返回翻译结果，不要添加任何解释或引号。`;

    const completion = await client.chat.completions.create({
      model: m,
      messages: [
        { role: 'system', content: sysPrompt },
        { role: 'user', content: text },
      ],
      temperature: 0.3,
    });

    return {
      sourceText: text,
      translatedText: completion.choices[0]?.message?.content?.trim() || '',
      sourceLang: LANG_MAP[sourceLang] || sourceLang,
      targetLang: LANG_MAP[targetLang] || targetLang,
      provider: p,
      model: m,
    };
  }

  getSupportedLanguages() {
    return Object.entries(LANG_MAP).map(([code, name]) => ({ code, name }));
  }
}

export const translationService = new TranslationService();
