require('dotenv').config({ path: '/opt/ai-agent-platform/server/.env' });
const crypto = require('crypto');
const key = Buffer.from(process.env.ENCRYPTION_KEY || '', 'hex');
console.log('KEY_BYTES=' + key.length);
const pt = 'sk-user-secret-abc-123';
const iv = crypto.randomBytes(12);
const c = crypto.createCipheriv('aes-256-gcm', key, iv);
const enc = Buffer.concat([c.update(pt, 'utf8'), c.final()]);
const tag = c.getAuthTag();
const d = crypto.createDecipheriv('aes-256-gcm', key, iv);
d.setAuthTag(tag);
const dec = Buffer.concat([d.update(enc), d.final()]).toString('utf8');
console.log('ROUNDTRIP_OK=' + (dec === pt));
